%% classDiagram
%%     %% Users
%%     class User {
%%         +int id
%%           firstname
%%           lastname
%%           email
%%           password
%%           country
%%         +hasMany(Transaction)
%%         +hasMany(AcheterService)
%%         +hasMany(RechargeBalance)
%%     }

%%     %% Transactions
%%     class Transaction {
%%         +int id
%%         +float amount
%%         +date date
%%           reference_id
%%           receipt
%%         +belongsTo(User)
%%     }

%%     %% Services
%%     class Services {
%%         +int id
%%           title
%%           description
%%         +date valid_until
%%           image
%%         +hasMany(PlanService)
%%     }

%%     %% PlanService
%%     class PlanService {
%%         +int id
%%         +int service_id
%%         +belongsTo(Services)
%%     }

%%     %% RechargeBalance
%%     class RechargeBalance {
%%         +int id
%%         +float price
%%         +float duration
%%         +date created_at
%%         +belongsTo(User)
%%     }

%%     %% AcheterService
%%     class AcheterService {
%%         +int id
%%         +float price
%%         +date datedebut
%%         +date datefin
%%         +date created_at
%%         +belongsTo(User)
%%         +belongsTo(PlanService)
%%     }

%%     %% TypeService
%%     class TypeService {
%%         +int id
%%         +float price
%%         +float duration
%%         +date created_at
%%         +belongsTo(PlanService)
%%     }

%%     User "1" --> "0..*" Transaction
%%     User "1" --> "0..*" AcheterService
%%     User "1" --> "0..*" RechargeBalance
%%     Transaction "0..*" --> "1" User
%%     Services "1" --> "0..*" PlanService
%%     PlanService "0..*" --> "1" Services
%%     RechargeBalance "0..*" --> "1" User
%%     AcheterService "0..*" --> "1" User
%%     AcheterService "0..*" --> "1" PlanService
%%     TypeService "0..*" --> "1" PlanService


classDiagram
    %% Users
    class User {
        +int id
        firstname
          lastname
          email
          password
          country
        +hasMany(Transaction)
        +hasMany(AcheterService)
        +hasMany(RechargeBalance)
    }

    %% Transactions
    class Transaction {
        +int id       
        +belongsTo(User)
    }

    %% Services
    class Services {
        +int id
          title
          description
        +hasMany(PlanService)
    }

    %% PlanService
    class PlanService {
        +int id
          image
          vidoe
             Link
        +belongsTo(Services)
    }

    %% RechargeBalance
    class RechargeBalance {
        +int id
         price
         duration
        +date date
        +belongsTo(User)
    }

    %% AcheterService
    class AcheterService {
        +int id
         price
        +date datedebut
        +date datefin
        +date created_at
        +belongsTo(User)
        +belongsTo(PlanService)
    }

    %% TypeService
    class TypeService {
        +int id
         price
         duration
        +date created_at
        +belongsTo(PlanService)
    }

    User "1" --> "0..*" Transaction : has many
    User "1" --> "0..*" AcheterService : has many
    User "1" --> "0..*" RechargeBalance : has many
    Transaction "0..*" --> "1" User : belongs to
    Services "1" --> "0..*" PlanService : has many
    PlanService "0..*" --> "1" Services : belongs to
    RechargeBalance "0..*" --> "1" User : belongs to
    AcheterService "0..*" --> "1" User : belongs to
    AcheterService "0..*" --> "1" PlanService : belongs to
    TypeService "0..*" --> "1" PlanService : belongs to
